services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - GOTENBERG_URL=http://gotenberg:3000
    depends_on:
      - gotenberg

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3030:3000"